#!/bin/bash
shopt -s extglob

ZAL_VERSION="1.10"
ZAL_VERSION_EXTENDED="1.10.2"

ZIMBRA_VERSION=$(sudo su - zimbra -c "zmcontrol -v" | tr -d '\n' | sed -r 's/.* ([0-9\.]+[0-9]).*/\1/')

echo "  Downloading the correct ZAL Version (${ZAL_VERSION_EXTENDED} for zimbra ${ZIMBRA_VERSION})..."
wget "https://openzal.org/${ZAL_VERSION}/zal-${ZAL_VERSION_EXTENDED}-${ZIMBRA_VERSION}.jar" -O "zal-${ZAL_VERSION_EXTENDED}-${ZIMBRA_VERSION}.jar"

echo "  Installing files..."
mkdir -p /opt/zimbra/lib/ext/ownCloud
rm /opt/zimbra/lib/ext/ownCloud/*.jar
cp "zal-${ZAL_VERSION_EXTENDED}-${ZIMBRA_VERSION}.jar" /opt/zimbra/lib/ext/ownCloud/
cp !(zal*).jar /opt/zimbra/lib/ext/ownCloud/
cp *.jar /opt/zimbra/lib/ext/ownCloud/

echo "  Deploying zimlet..."
cp -f tk_barrydegraaff_owncloud_zimlet.zip /tmp
su - zimbra -c "zmzimletctl deploy /tmp/tk_barrydegraaff_owncloud_zimlet.zip"
su - zimbra -c "zmprov fc all"
rm -Rf /tmp/tk_barrydegraaff_owncloud_zimlet.zip

echo -e "\n\n  Extension jar and zimlet deployed, restart your mailbox server to load the extension.\n\n"
